In [1]:
import os
import configparser
import sys

# 設定の読み込み
config = configparser.ConfigParser()
config_path = "../config.ini"
config.read(config_path)
PROJECT_DIR = config["paths"]["project_dir"]
sys.path.append(PROJECT_DIR)


import torch

In [2]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
temp = X[:, 1] == 2
temp

tensor([ True, False, False])

In [5]:
temp.sum()

tensor(1)

In [6]:
temp.float()

tensor([1., 0., 0.])

In [7]:
input_size = 10
hidden_unit_size = 64
output_size = 1
num_hidden_layers = 3

# 入力層から最初の隠れ層
params_input_to_hidden = (input_size * hidden_unit_size) + hidden_unit_size

# 隠れ層から隠れ層
params_hidden_to_hidden = (hidden_unit_size * hidden_unit_size) + hidden_unit_size
params_hidden_layers = params_hidden_to_hidden * (num_hidden_layers - 1)

# 最後の隠れ層から出力層
params_hidden_to_output = (hidden_unit_size * output_size) + output_size

# 総パラメータ数
total_params = params_input_to_hidden + params_hidden_layers + params_hidden_to_output
total_params

9089