In [1]:
import torch

In [2]:
bounds = torch.tensor([
    [0, 2], [8, 7]
])

bounds

tensor([[0, 2],
        [8, 7]])

In [8]:
train_x = torch.randint(
            low=int(bounds[0, 0]),
            high=int(bounds[1, 0]),
            size=(1, bounds.size(1)),
        )

train_x

tensor([[2, 4]])

In [12]:
bounds[1] - bounds[0]

[
    ["第１変数の下限", "第２変数の下限", ...], ["第１変数の上限", "第２変数の上限", ...]
]

tensor([8, 5])

In [13]:
import torch

def generate_integer_samples(bounds, n, device=torch.device("cpu")):
    """
    整数をランダムにサンプリングして、n 行 m 列の torch.Tensor を生成します。
    重複のない n サンプルが得られるまでサンプリングを繰り返します。
    
    Parameters:
    - bounds: list of list, 変数の下限と上限のリスト
    - n: int, サンプル数
    - device: torch.device, テンソルを配置するデバイス
    
    Returns:
    - torch.Tensor, n 行 m 列のテンソル
    """
    lower_bounds = torch.tensor(bounds[0], device=device)
    upper_bounds = torch.tensor(bounds[1], device=device) + 1  # 上限を含むようにするため
    
    m = lower_bounds.shape[0]
    samples = set()

    while len(samples) < n:
        new_samples = torch.randint(low=lower_bounds, high=upper_bounds, size=(n, m), device=device)
        for sample in new_samples:
            samples.add(tuple(sample.tolist()))  # 重複を避けるためにタプルに変換してセットに追加

        # 必要なサンプル数に達している場合は終了
        if len(samples) >= n:
            break

    # 最終的なサンプルをテンソルに変換
    unique_samples = torch.tensor(list(samples)[:n], device=device)
    return unique_samples

# テスト
bounds = [[0, 0], [4, 4]]
n = 10
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
samples = generate_integer_samples(bounds, n, device)
print(samples)

TypeError: randint() received an invalid combination of arguments - got (device=torch.device, size=tuple, high=Tensor, low=Tensor, ), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int high, tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int low, int high, tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [15]:
import torch

def generate_integer_samples(bounds, n, device=torch.device("cpu")):
    """
    整数をランダムにサンプリングして、n 行 m 列の torch.Tensor を生成します。
    重複のない n サンプルが得られるまでサンプリングを繰り返します。
    
    Parameters:
    - bounds: list of list, 変数の下限と上限のリスト
    - n: int, サンプル数
    - device: torch.device, テンソルを配置するデバイス
    
    Returns:
    - torch.Tensor, n 行 m 列のテンソル
    """
    lower_bounds = torch.tensor(bounds[0], device=device, dtype=torch.int)
    upper_bounds = torch.tensor(bounds[1], device=device, dtype=torch.int)

    m = lower_bounds.shape[0]
    samples = set()

    while len(samples) < n:
        new_samples = []
        for _ in range(n):
            sample = []
            for i in range(m):
                sample.append(torch.randint(low=lower_bounds[i].item(), high=upper_bounds[i].item() + 1, size=(1,), device=device).item())
            new_samples.append(tuple(sample))
        
        for sample in new_samples:
            samples.add(sample)

        if len(samples) >= n:
            break

    unique_samples = torch.tensor(list(samples)[:n], device=device)
    return unique_samples

# テスト
bounds = [[0, 0, 0, 0, 0, 0], [4, 5, 6, 7, 8, 9]]
n = 10
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
samples = generate_integer_samples(bounds, n, device)
print(samples)

tensor([[0, 2, 5, 7, 8, 8],
        [4, 0, 5, 6, 2, 6],
        [0, 3, 4, 4, 0, 4],
        [1, 0, 2, 1, 2, 1],
        [4, 1, 2, 1, 7, 5],
        [3, 3, 6, 1, 7, 0],
        [3, 5, 5, 2, 2, 7],
        [1, 0, 2, 6, 7, 4],
        [2, 0, 1, 2, 1, 9],
        [1, 1, 5, 6, 1, 6]])
