In [1]:
import torch

In [2]:
bounds = torch.tensor([
    [0, 2], [8, 7]
])

bounds

tensor([[0, 2],
        [8, 7]])

In [8]:
train_x = torch.randint(
            low=int(bounds[0, 0]),
            high=int(bounds[1, 0]),
            size=(1, bounds.size(1)),
        )

train_x

tensor([[2, 4]])

In [12]:
bounds[1] - bounds[0]

[
    ["第１変数の下限", "第２変数の下限", ...], ["第１変数の上限", "第２変数の上限", ...]
]

tensor([8, 5])

In [13]:
import torch

def generate_integer_samples(bounds, n, device=torch.device("cpu")):
    """
    整数をランダムにサンプリングして、n 行 m 列の torch.Tensor を生成します。
    重複のない n サンプルが得られるまでサンプリングを繰り返します。
    
    Parameters:
    - bounds: list of list, 変数の下限と上限のリスト
    - n: int, サンプル数
    - device: torch.device, テンソルを配置するデバイス
    
    Returns:
    - torch.Tensor, n 行 m 列のテンソル
    """
    lower_bounds = torch.tensor(bounds[0], device=device)
    upper_bounds = torch.tensor(bounds[1], device=device) + 1  # 上限を含むようにするため
    
    m = lower_bounds.shape[0]
    samples = set()

    while len(samples) < n:
        new_samples = torch.randint(low=lower_bounds, high=upper_bounds, size=(n, m), device=device)
        for sample in new_samples:
            samples.add(tuple(sample.tolist()))  # 重複を避けるためにタプルに変換してセットに追加

        # 必要なサンプル数に達している場合は終了
        if len(samples) >= n:
            break

    # 最終的なサンプルをテンソルに変換
    unique_samples = torch.tensor(list(samples)[:n], device=device)
    return unique_samples

# テスト
bounds = [[0, 0], [4, 4]]
n = 10
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
samples = generate_integer_samples(bounds, n, device)
print(samples)

TypeError: randint() received an invalid combination of arguments - got (device=torch.device, size=tuple, high=Tensor, low=Tensor, ), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int high, tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (int low, int high, tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [15]:
import torch

def generate_integer_samples(bounds, n, device=torch.device("cpu")):
    """
    整数をランダムにサンプリングして、n 行 m 列の torch.Tensor を生成します。
    重複のない n サンプルが得られるまでサンプリングを繰り返します。
    
    Parameters:
    - bounds: list of list, 変数の下限と上限のリスト
    - n: int, サンプル数
    - device: torch.device, テンソルを配置するデバイス
    
    Returns:
    - torch.Tensor, n 行 m 列のテンソル
    """
    lower_bounds = torch.tensor(bounds[0], device=device, dtype=torch.int)
    upper_bounds = torch.tensor(bounds[1], device=device, dtype=torch.int)

    m = lower_bounds.shape[0]
    samples = set()

    while len(samples) < n:
        new_samples = []
        for _ in range(n):
            sample = []
            for i in range(m):
                sample.append(torch.randint(low=lower_bounds[i].item(), high=upper_bounds[i].item() + 1, size=(1,), device=device).item())
            new_samples.append(tuple(sample))
        
        for sample in new_samples:
            samples.add(sample)

        if len(samples) >= n:
            break

    unique_samples = torch.tensor(list(samples)[:n], device=device)
    return unique_samples

# テスト
bounds = [[0, 0, 0, 0, 0, 0], [4, 5, 6, 7, 8, 9]]
n = 10
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
samples = generate_integer_samples(bounds, n, device)
print(samples)

tensor([[0, 2, 5, 7, 8, 8],
        [4, 0, 5, 6, 2, 6],
        [0, 3, 4, 4, 0, 4],
        [1, 0, 2, 1, 2, 1],
        [4, 1, 2, 1, 7, 5],
        [3, 3, 6, 1, 7, 0],
        [3, 5, 5, 2, 2, 7],
        [1, 0, 2, 6, 7, 4],
        [2, 0, 1, 2, 1, 9],
        [1, 1, 5, 6, 1, 6]])


In [10]:
import torch 

train_x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.int)
train_y = torch.tensor([6, 5, 4, 3, 2, 1], dtype=torch.int)

train_x[train_y.argmax() if "a" == "b" else train_y.argmin()].item()

6

In [8]:
# def schubert_function(X):
#     r"""
#     $f(x_1, x_2) = \prod_{i=1}^2 \left( \sum_{j=1}^5 j \cos((j + 1)x_i + j) \right)$
#     """
#     j = torch.arange(1, 6).float()
#     sum1 = torch.sum(j * torch.cos((j + 1) * X[:, 0:1] + j), dim=1)
#     sum2 = torch.sum(j * torch.cos((j + 1) * X[:, 1:2] + j), dim=1)
#     return sum1 * sum2


import sys
from path_info import PROJECT_DIR
sys.path.append(PROJECT_DIR)
from src.utils_benchmark_functions_2 import schubert_function

objective = -schubert_function
objective

TypeError: bad operand type for unary -: 'function'

$$\alpha'(x) = \lambda_{1} (1 - g(x)) \alpha(x) + \lambda_{2}g(x) \alpha(x)$$

In [13]:
from botorch.acquisition import UpperConfidenceBound


class CustomUpperConfidenceBound(UpperConfidenceBound):
    def forward(self, X):
        r"""
        Evaluate the Upper Confidence Bound (UCB) acquisition function at the points X.
        """
        posterior = self.model.posterior(X)
        mean = posterior.mean
        std = posterior.variance.sqrt()
        return mean + self.beta * std

In [15]:
import warnings
import torch
from botorch.acquisition import UpperConfidenceBound
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.optim import optimize_acqf
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood

warnings.filterwarnings("ignore")

# データを用意 (X_train, Y_train)
X_train = torch.rand(10, 2)  # 入力データの例
Y_train = torch.sin(X_train[:, 0]).unsqueeze(-1)  # 出力データの例 (2次元に変換)

# モデルの作成と訓練
model = SingleTaskGP(X_train, Y_train)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_mll(mll)

# 最適化範囲の定義
bounds = torch.stack([torch.zeros(2), torch.ones(2)])

# 最適化ループを10回実行
for i in range(10):
    # UCB獲得関数のインスタンス化
    acq_function = UpperConfidenceBound(model, beta=0.1)
    
    candidate, acq_value = optimize_acqf(
        acq_function,
        bounds=bounds,
        q=1,
        num_restarts=5,
        raw_samples=20,
    )
    
    # 新しい候補点を訓練データに追加
    X_train = torch.cat([X_train, candidate])
    Y_train = torch.cat([Y_train, torch.sin(candidate[:, 0]).unsqueeze(-1)])
    
    # モデルを再訓練
    model = SingleTaskGP(X_train, Y_train)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(mll)
    
    print(f"Iteration {i+1}")
    print("最適な候補:", candidate)
    print("獲得関数の値:", acq_value)

Iteration 1
最適な候補: tensor([[1., 0.]])
獲得関数の値: tensor(0.8670)
Iteration 2
最適な候補: tensor([[1., 1.]])
獲得関数の値: tensor(0.8767)
Iteration 3
最適な候補: tensor([[1.0000, 0.6511]])
獲得関数の値: tensor(0.8567)
Iteration 4
最適な候補: tensor([[1.0000, 0.8342]])
獲得関数の値: tensor(0.8476)
Iteration 5
最適な候補: tensor([[1.0000, 0.1980]])
獲得関数の値: tensor(0.8452)
Iteration 6
最適な候補: tensor([[1.0000, 0.8471]])
獲得関数の値: tensor(0.8450)
Iteration 7
最適な候補: tensor([[1.0000, 0.2297]])
獲得関数の値: tensor(0.8438)
Iteration 8
最適な候補: tensor([[1., 0.]])
獲得関数の値: tensor(0.8443)
Iteration 9
最適な候補: tensor([[1.0000, 0.8024]])
獲得関数の値: tensor(0.8438)
Iteration 10
最適な候補: tensor([[1.0000, 0.4761]])
獲得関数の値: tensor(0.8439)


In [131]:
import torch
import plotly.graph_objects as go
import numpy as np

def objective_function(x):
    # Ackley function parameters
    a = 20
    b = 0.2
    c = 2 * torch.pi

    # Calculate the Ackley function
    term1 = -a * torch.exp(-b * torch.sqrt(0.5 * (x[:, 0]**2 + x[:, 1]**2)))
    term2 = -torch.exp(0.5 * (torch.cos(c * x[:, 0]) + torch.cos(c * x[:, 1])))
    
    # Ackley function value
    ackley_value = term1 + term2 + a + torch.exp(torch.tensor(1.0))
    
    # Unsqueeze to match the expected output shape and scale
    return - ackley_value.unsqueeze(-1) * (1/5)


# グリッドの作成
grid_size = 100
x = np.linspace(-1, 1, grid_size)
y = np.linspace(-1, 1, grid_size)
X, Y = np.meshgrid(x, y)
XY = np.vstack([X.ravel(), Y.ravel()]).T

# 目的関数の値を計算
XY_tensor = torch.tensor(XY, dtype=torch.float32)
Z = objective_function(XY_tensor).numpy().reshape(grid_size, grid_size)

# 3Dプロットの作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title='Objective Function Surface',
                  scene=dict(
                      xaxis_title='X1',
                      yaxis_title='X2',
                      zaxis_title='Objective Value'),
                  width=800, height=800)
fig.show()

In [132]:
import torch
from botorch.acquisition import UpperConfidenceBound, AcquisitionFunction
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.optim import optimize_acqf
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood

# カスタム獲得関数クラスの定義
class CustomAcquisitionFunction(AcquisitionFunction):
    def __init__(self, model, lambda1, g):
        super().__init__(model)
        self.lambda1 = lambda1
        self.lambda2 = 1 - lambda1
        self.g = g
        self.ucb = UpperConfidenceBound(model, beta=0.1)
    
    def forward(self, X):
        alpha_x = self.ucb(X)
        g_x = self.g(X)
        # return self.lambda1 * g_x * alpha_x - self.lambda2 * (1 - g_x)
        return self.lambda1 * (1 - g_x) * alpha_x - self.lambda2 * g_x

# 制約関数 g(x) の定義
def g(x):
    if x.shape[1] > 1:
        diff = torch.abs(x[:, 0] - x[:, 1])
        return torch.exp(-diff).unsqueeze(-1)
    else:
        return torch.zeros_like(x[:, 0]).unsqueeze(-1)

def objective_function(x):
    # Ackley function parameters
    a = 20
    b = 0.2
    c = 2 * torch.pi

    # Calculate the Ackley function
    term1 = -a * torch.exp(-b * torch.sqrt(0.5 * (x[:, 0]**2 + x[:, 1]**2)))
    term2 = -torch.exp(0.5 * (torch.cos(c * x[:, 0]) + torch.cos(c * x[:, 1])))
    
    # Ackley function value
    ackley_value = term1 + term2 + a + torch.exp(torch.tensor(1.0))
    
    # Unsqueeze to match the expected output shape and scale
    return - ackley_value.unsqueeze(-1) * (1/5)

# データを用意 (X_train, Y_train)
X_train = torch.rand(10, 2)  # 入力データの例
Y_train = objective_function(X_train)  # 目的関数の値 (2次元に変換)

# モデルの作成と訓練
model = SingleTaskGP(X_train, Y_train)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_mll(mll)

# カスタム獲得関数のインスタンス化
lambda1 = 0.5
acq_function = CustomAcquisitionFunction(model, lambda1, g)

# 最適化範囲の定義
bounds = torch.tensor([[-4, -4], [4, 4]]).float()

# 最適化ループを10回実行
for i in range(40):
    candidate, acq_value = optimize_acqf(
        acq_function,
        bounds=bounds,
        q=1,
        num_restarts=5,
        raw_samples=20,
    )
    
    # 新しい候補点を訓練データに追加
    X_train = torch.cat([X_train, candidate])
    Y_train = torch.cat([Y_train, objective_function(candidate)])
    
    # モデルを再訓練
    model = SingleTaskGP(X_train, Y_train)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(mll)
    
    print(f"Iteration {i+1}")
    print("最適な候補:", candidate)
    print("獲得関数の値:", acq_value)

Iteration 1
最適な候補: tensor([[ 0.0869, -0.1177]])
獲得関数の値: tensor(-0.1686)
Iteration 2
最適な候補: tensor([[ 0.0869, -0.1176]])
獲得関数の値: tensor(-0.1686)
Iteration 3
最適な候補: tensor([[ 0.0870, -0.1173]])
獲得関数の値: tensor(-0.1686)
Iteration 4
最適な候補: tensor([[ 0.0871, -0.1177]])
獲得関数の値: tensor(-0.1686)
Iteration 5
最適な候補: tensor([[ 0.0869, -0.1176]])
獲得関数の値: tensor(-0.1686)
Iteration 6
最適な候補: tensor([[ 0.0869, -0.1178]])
獲得関数の値: tensor(-0.1686)
Iteration 7
最適な候補: tensor([[ 0.0869, -0.1175]])
獲得関数の値: tensor(-0.1686)
Iteration 8
最適な候補: tensor([[ 0.0868, -0.1177]])
獲得関数の値: tensor(-0.1686)
Iteration 9
最適な候補: tensor([[ 0.0871, -0.1177]])
獲得関数の値: tensor(-0.1686)
Iteration 10
最適な候補: tensor([[ 0.0869, -0.1176]])
獲得関数の値: tensor(-0.1686)
Iteration 11
最適な候補: tensor([[ 0.0871, -0.1176]])
獲得関数の値: tensor(-0.1686)
Iteration 12
最適な候補: tensor([[1.6055, 1.4484]])
獲得関数の値: tensor(-0.2709)
Iteration 13
最適な候補: tensor([[ 0.0870, -0.1176]])
獲得関数の値: tensor(-0.1686)
Iteration 14
最適な候補: tensor([[ 0.0869, -0.1176]])
獲得関数の値: tenso

In [41]:
X_train[Y_train.argmax()], Y_train.max()

(tensor([0.0430, 0.0504]), tensor(-0.0044))

In [127]:
import torch
from botorch.acquisition import UpperConfidenceBound, AcquisitionFunction
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.optim import optimize_acqf
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood
import plotly.graph_objects as go
import numpy as np

# カスタム獲得関数クラスの定義
class CustomAcquisitionFunction(AcquisitionFunction):
    def __init__(self, model, lambda1, g):
        super().__init__(model)
        self.lambda1 = lambda1
        self.lambda2 = 1 - lambda1
        self.g = g
        self.ucb = UpperConfidenceBound(model, beta=0.1)
    
    def forward(self, X):
        alpha_x = self.ucb(X)
        # print(f'alpha_x: {alpha_x}')

        g_x = self.g(X)

        # print()
        print(f'g_x: {g_x.mean()}, alaph_x: {alpha_x.mean()}')
        # print(f'g_x.shape: {g_x.shape}')
        # print()
        # return self.lambda1 * (1 - g_x) * alpha_x - self.lambda2 * g_x * alpha_x
        # return self.lambda1 * (1 - g_x) * alpha_x - self.lambda2 * (1 - g_x)
        # return self.lambda1 * alpha_x + self.lambda2 * g_x


        # return self.lambda1 * torch.log(g_x) + self.lambda2 * torch.log(alpha_x)
        return self.lambda1 * g_x + self.lambda2 * alpha_x

# 制約関数 g(x) の定義
def g(x):
    if x.ndim == 3 and x.shape[1] == 1:
        x = x.squeeze(1)  # 余分な次元を削除
    diff = torch.abs(x[:, 0] - x[:, 1])
    return torch.exp(-diff)

# 目的関数の定義 (符号を反転させた2変数のSphere関数)
def objective_function(x):
    return -(x[:, 0]**2 + x[:, 1]**2).unsqueeze(-1) * (1/5)

# データを用意 (X_train, Y_train)
X_train = torch.tensor([[-4.,4.]])  # 入力データの例
Y_train = objective_function(X_train)  # 目的関数の値 (2次元に変換)

# モデルの作成と訓練
model = SingleTaskGP(X_train, Y_train)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_mll(mll)

# カスタム獲得関数のインスタンス化
lambda1 = 0.1
acq_function = CustomAcquisitionFunction(model, lambda1, g)

# 最適化範囲の定義
bounds = torch.tensor([[-4, -4], [4, 4]]).float()

# 最適化ループを10回実行
for i in range(30):
    candidate, acq_value = optimize_acqf(
        acq_function,
        bounds=bounds,
        q=1,
        num_restarts=5,
        raw_samples=20,
    )
    
    # 新しい候補点を訓練データに追加
    X_train = torch.cat([X_train, candidate])
    Y_train = torch.cat([Y_train, objective_function(candidate)])
    
    # モデルを再訓練
    model = SingleTaskGP(X_train, Y_train)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(mll)
    
    # print(f"Iteration {i+1}")
    # print("最適な候補:", candidate)
    # print("獲得関数の値:", acq_value)

# 目的関数のプロット
grid_size = 30
x = np.linspace(-4, 4, grid_size)
y = np.linspace(-4, 4, grid_size)
X, Y = np.meshgrid(x, y)
XY = np.vstack([X.ravel(), Y.ravel()]).T

# 目的関数の値を計算
XY_tensor = torch.tensor(XY, dtype=torch.float32)
Z = objective_function(XY_tensor).numpy().reshape(grid_size, grid_size)

# 評価点と評価値の取得
X_eval = X_train.numpy()
Y_eval = Y_train.numpy()

# カラーリストの作成（最初の点は赤、最後の点は青、その他はグラデーション）
colors = ['red'] + ['rgba(0,0,255,{})'.format(i/len(X_eval)) for i in range(1, len(X_eval)-1)] + ['blue']

# 3Dプロットの作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, opacity=0.7)])
fig.add_trace(go.Scatter3d(x=X_eval[:, 0], y=X_eval[:, 1], z=Y_eval.flatten(),
                           mode='markers+lines', marker=dict(size=5, color=colors, symbol='circle'),
                           line=dict(color='grey', width=2)))

fig.update_layout(title='Objective Function Surface with Evaluation Points',
                  scene=dict(
                      xaxis_title='X1',
                      yaxis_title='X2',
                      zaxis_title='Objective Value'),
                  width=800, height=800)

fig.show()

g_x: 0.2581022083759308, alaph_x: -5.783881187438965
g_x: 0.4680684208869934, alaph_x: -5.783880710601807
g_x: 0.5415037870407104, alaph_x: -5.783880710601807
g_x: 0.8472387194633484, alaph_x: -5.783880710601807
g_x: 0.7505170702934265, alaph_x: -5.783880710601807
g_x: 0.8674113154411316, alaph_x: -5.783880710601807
g_x: 0.7757920622825623, alaph_x: -5.783880710601807
g_x: 0.886320948600769, alaph_x: -5.783880710601807
g_x: 0.8379610180854797, alaph_x: -5.783880710601807
g_x: 0.8932115435600281, alaph_x: -5.783880710601807
g_x: 0.8897018432617188, alaph_x: -5.783880710601807
g_x: 0.8921381235122681, alaph_x: -5.783880710601807
g_x: 0.9517624974250793, alaph_x: -5.783880710601807
g_x: 0.9685168266296387, alaph_x: -5.783880710601807
g_x: 0.9688702821731567, alaph_x: -5.783880710601807
g_x: 0.9878160357475281, alaph_x: -5.783880710601807
g_x: 0.9831584095954895, alaph_x: -5.783880710601807
g_x: 0.9886663556098938, alaph_x: -5.783880710601807
g_x: 0.970831036567688, alaph_x: -5.78388071060

In [128]:
X_train

tensor([[-4.0000,  4.0000],
        [ 2.4123,  2.4123],
        [-0.6896, -0.6896],
        [-3.8296, -3.8296],
        [-0.9437, -0.9437],
        [ 0.6450,  0.6450],
        [-1.8766, -1.8766],
        [-0.1769, -0.1769],
        [ 0.9062,  0.9062],
        [ 0.7948,  0.7948],
        [-2.9658, -2.9658],
        [-1.4928, -1.4928],
        [-3.5224, -3.5224],
        [-1.3296, -1.3296],
        [-1.6326, -1.6326],
        [ 0.3558,  0.3558],
        [-0.9647, -0.9647],
        [-3.0566, -3.0566],
        [ 1.4737,  1.4737],
        [-0.1975, -0.1975],
        [ 1.8292,  1.8292],
        [-0.6363, -0.6363],
        [ 0.5650,  0.5650],
        [-0.1273, -0.1273],
        [-1.0981, -1.0981],
        [-1.6556, -1.6556],
        [ 2.8118,  2.8118],
        [ 1.7461,  1.7461],
        [ 1.9932,  1.9932],
        [-1.7601, -1.7601],
        [ 3.1992,  3.1992]])

In [129]:
X_train[Y_train.argmax()], Y_train.max(), Y_train.argmax()

(tensor([-0.1273, -0.1273]), tensor(-0.0065), tensor(23))

In [75]:
sum(abs(X_train[:, 0] - X_train[:, 1]))

tensor(71.6719)

In [76]:
101, 72, 81, 95, 71

(101, 72, 81, 95)

In [89]:
temp1 = torch.tensor([101, 72, 81, 95, 71]) 
temp2 = torch.tensor([1, 2, 3, 4, 5])

temp1 * temp2 

tensor([101, 144, 243, 380, 355])

# ackley

In [134]:
import torch
from botorch.acquisition import UpperConfidenceBound, AcquisitionFunction
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.optim import optimize_acqf
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood
import plotly.graph_objects as go
import numpy as np

# カスタム獲得関数クラスの定義
class CustomAcquisitionFunction(AcquisitionFunction):
    def __init__(self, model, lambda1, g):
        super().__init__(model)
        self.lambda1 = lambda1
        self.lambda2 = 1 - lambda1
        self.g = g
        self.ucb = UpperConfidenceBound(model, beta=0.1)
    
    def forward(self, X):
        alpha_x = self.ucb(X)
        # print(f'alpha_x: {alpha_x}')

        g_x = self.g(X)

        # print()
        print(f'g_x: {g_x.mean()}, alaph_x: {alpha_x.mean()}')
        # print(f'g_x.shape: {g_x.shape}')
        # print()
        # return self.lambda1 * (1 - g_x) * alpha_x - self.lambda2 * g_x * alpha_x
        # return self.lambda1 * (1 - g_x) * alpha_x - self.lambda2 * (1 - g_x)
        # return self.lambda1 * alpha_x + self.lambda2 * g_x


        # return self.lambda1 * torch.log(g_x) + self.lambda2 * torch.log(alpha_x)
        return self.lambda1 * g_x + self.lambda2 * alpha_x

# 制約関数 g(x) の定義
def g(x):
    if x.ndim == 3 and x.shape[1] == 1:
        x = x.squeeze(1)  # 余分な次元を削除
    diff = torch.abs(x[:, 0] - x[:, 1])
    return torch.exp(-diff)


def objective_function(x):
    # Ackley function parameters
    a = 20
    b = 0.2
    c = 2 * torch.pi

    # Calculate the Ackley function
    term1 = -a * torch.exp(-b * torch.sqrt(0.5 * (x[:, 0]**2 + x[:, 1]**2)))
    term2 = -torch.exp(0.5 * (torch.cos(c * x[:, 0]) + torch.cos(c * x[:, 1])))
    
    # Ackley function value
    ackley_value = term1 + term2 + a + torch.exp(torch.tensor(1.0))
    
    # Unsqueeze to match the expected output shape and scale
    return - ackley_value.unsqueeze(-1)


# データを用意 (X_train, Y_train)
X_train = torch.tensor([[-4.,4.]])  # 入力データの例
Y_train = objective_function(X_train)  # 目的関数の値 (2次元に変換)

# モデルの作成と訓練
model = SingleTaskGP(X_train, Y_train)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_mll(mll)

# カスタム獲得関数のインスタンス化
lambda1 = 0.1
acq_function = CustomAcquisitionFunction(model, lambda1, g)

# 最適化範囲の定義
bounds = torch.tensor([[-4, -4], [4, 4]]).float()

# 最適化ループを10回実行
for i in range(30):
    candidate, acq_value = optimize_acqf(
        acq_function,
        bounds=bounds,
        q=1,
        num_restarts=5,
        raw_samples=20,
    )
    
    # 新しい候補点を訓練データに追加
    X_train = torch.cat([X_train, candidate])
    Y_train = torch.cat([Y_train, objective_function(candidate)])
    
    # モデルを再訓練
    model = SingleTaskGP(X_train, Y_train)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(mll)
    
    # print(f"Iteration {i+1}")
    # print("最適な候補:", candidate)
    # print("獲得関数の値:", acq_value)

# 目的関数のプロット
grid_size = 30
x = np.linspace(-4, 4, grid_size)
y = np.linspace(-4, 4, grid_size)
X, Y = np.meshgrid(x, y)
XY = np.vstack([X.ravel(), Y.ravel()]).T

# 目的関数の値を計算
XY_tensor = torch.tensor(XY, dtype=torch.float32)
Z = objective_function(XY_tensor).numpy().reshape(grid_size, grid_size)

# 評価点と評価値の取得
X_eval = X_train.numpy()
Y_eval = Y_train.numpy()

# カラーリストの作成（最初の点は赤、最後の点は青、その他はグラデーション）
colors = ['red'] + ['rgba(0,0,255,{})'.format(i/len(X_eval)) for i in range(1, len(X_eval)-1)] + ['blue']

# 3Dプロットの作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, opacity=0.7)])
fig.add_trace(go.Scatter3d(x=X_eval[:, 0], y=X_eval[:, 1], z=Y_eval.flatten(),
                           mode='markers+lines', marker=dict(size=5, color=colors, symbol='circle'),
                           line=dict(color='grey', width=2)))

fig.update_layout(title='Objective Function Surface with Evaluation Points',
                  scene=dict(
                      xaxis_title='X1',
                      yaxis_title='X2',
                      zaxis_title='Objective Value'),
                  width=800, height=800)

fig.show()

g_x: 0.2332451045513153, alaph_x: -10.397271156311035
g_x: 0.5615055561065674, alaph_x: -10.397272109985352
g_x: 0.6040605306625366, alaph_x: -10.397272109985352
g_x: 0.5986688733100891, alaph_x: -10.397272109985352
g_x: 0.6489078998565674, alaph_x: -10.397272109985352
g_x: 0.6446404457092285, alaph_x: -10.397272109985352
g_x: 0.6535264253616333, alaph_x: -10.397272109985352
g_x: 0.6605949997901917, alaph_x: -10.397272109985352
g_x: 0.5998398065567017, alaph_x: -10.397272109985352
g_x: 0.6811986565589905, alaph_x: -10.397272109985352
g_x: 0.6724303364753723, alaph_x: -10.397272109985352
g_x: 0.6827137470245361, alaph_x: -10.397272109985352
g_x: 0.6825804710388184, alaph_x: -10.397272109985352
g_x: 0.6841500997543335, alaph_x: -10.397272109985352
g_x: 0.6842473149299622, alaph_x: -10.397272109985352
g_x: 0.6817710995674133, alaph_x: -10.397272109985352
g_x: 0.6846836805343628, alaph_x: -10.397272109985352
g_x: 0.6864310503005981, alaph_x: -10.397272109985352
g_x: 0.674140989780426, alap

In [136]:
X_train

tensor([[-4.0000,  4.0000],
        [-0.3988, -0.3988],
        [ 3.7298,  3.7298],
        [-3.5504, -3.5505],
        [ 2.4892,  2.4892],
        [-0.6453, -0.6453],
        [ 2.6077,  2.6077],
        [ 3.0679,  3.0679],
        [ 0.3921,  0.3921],
        [-1.5743, -1.5743],
        [-0.0270, -0.0270],
        [-2.2205, -2.2205],
        [-1.6546, -1.6546],
        [ 2.3165,  2.3165],
        [-3.1285, -3.1285],
        [-0.0591, -0.0591],
        [ 2.4526,  2.4526],
        [-0.4615, -0.4615],
        [-2.3334, -2.3334],
        [ 0.7902,  0.7902],
        [-1.4321, -1.4321],
        [ 1.0299,  1.0299],
        [-2.4267, -2.4267],
        [-3.6972, -3.6972],
        [-1.8196, -1.8196],
        [-3.3096, -3.3096],
        [-3.5124, -3.5125],
        [-0.0943, -0.0943],
        [-3.7574, -3.7574],
        [ 2.8764,  2.8764],
        [-0.3534, -0.3534]])

In [135]:
X_train[Y_train.argmax()], Y_train.max(), Y_train.argmax()


(tensor([-0.0270, -0.0270]), tensor(-0.1463), tensor(10))