In [1]:
import sys
from path_info import PROJECT_DIR
sys.path.append(PROJECT_DIR)

import torch

from src.utils_benchmark_functions_2 import test_function
from src.utils_benchmark_functions import discretize_function
from src.botorch_wrapper import DiscreteBO 

In [2]:
import numpy as np
import plotly.graph_objects as go

def test_function(x):
    return np.exp(-(x - 2) ** 2) + np.exp(-(x - 6) ** 2 / 10) + 1 / (np.exp(x ** 2) + 1)

# Generate x values
x = np.linspace(-5, 15, 400)
y = test_function(x)

# Create the plot
fig = go.Figure()

fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='test_function'))

# Update layout
fig.update_layout(
    title="Plot of the Test Function",
    xaxis_title="x",
    yaxis_title="f(x)"
)

# Show the plot
fig.show()


In [16]:
import torch

# Define the bounds
bounds = torch.tensor([[-2], [10]])

def sample_integers(bounds, num_samples):
    lower_bound, upper_bound = bounds[0, 0].item(), bounds[1, 0].item()
    samples = torch.randint(lower_bound, upper_bound + 1, (num_samples,))
    return samples

# Number of samples to draw
num_samples = 2

# Sample integers
samples = sample_integers(bounds, num_samples)
print(samples)

tensor([-2,  4])


In [7]:
X_init = torch.randint(-50, 601, (5, 3)).double()
X_init

tensor([[151.,  -2., 419.],
        [ 61., 242., 584.],
        [282., -15., 151.],
        [ 85.,  -8., 203.],
        [-21., 210., 180.]], dtype=torch.float64)

In [9]:
# Generate initial samples
X_init = torch.Tensor([[-2], [10]])
Y_init = test_function(X_init).unsqueeze(-1)

Y_init

tensor([[[0.2017]],

        [[0.2118]]])

In [4]:
# Initialize bounds for the optimization
bounds = torch.tensor([[-2.], [10.]])
    
# Generate initial samples
X_init = torch.Tensor([[-2], [10]])
Y_init = - test_function(X_init)

# Create an instance of DiscreteBO and initialize it
bo = DiscreteBO(bounds=bounds)
bo.initialize(X_init, Y_init)
    
# Optimization loop
for i in range(5):
    new_X = bo.step()
    new_Y = - test_function(new_X)
    bo.update(new_X, new_Y) 
    print(f"Iteration {i+1}: Suggested point: {new_X.numpy()}, Function value: {new_Y.numpy()}")

print()
print(f"Best value found: {bo.train_Y.min().item()}")
print(f"Best point found: {bo.train_X[bo.train_Y.argmin()].numpy()}")

/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_53573/1743148316.py:5: RuntimeWarning:

overflow encountered in exp

/Users/keisukeonoue/ws/constrained_BO/src/botorch_wrapper.py:107: InputDataWarning:

The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:257: InputDataWarning:

Input data is not contained to the unit cube. Please consider min-max scaling the input data.

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:260: InputDataWarning:

Data is not standardized (std = tensor([0.1289]), mean = tensor([-0.1108])). Please consider scaling the input to zero mean and unit variance.

/Users/keisukeonoue/ws/constrained_BO/s

Iteration 1: Suggested point: [[-1.]], Function value: [[-0.27651143]]
Iteration 2: Suggested point: [[3.]], Function value: [[-0.7745725]]


/Users/keisukeonoue/ws/constrained_BO/src/botorch_wrapper.py:107: InputDataWarning:

The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:257: InputDataWarning:

Input data is not contained to the unit cube. Please consider min-max scaling the input data.

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:260: InputDataWarning:

Data is not standardized (std = tensor([0.3228]), mean = tensor([-0.3182])). Please consider scaling the input to zero mean and unit variance.

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/scipy/optimize/_numdiff.py:592: RuntimeWarning:

invalid value encountered in subtract

/User

Iteration 3: Suggested point: [[9.]], Function value: [[-0.40656966]]
Iteration 4: Suggested point: [[-0.]], Function value: [[-0.5456394]]
Iteration 5: Suggested point: [[6.]], Function value: [[-1.0000001]]

Best value found: -1.0000001192092896
Best point found: [6.]


/Users/keisukeonoue/ws/constrained_BO/src/botorch_wrapper.py:107: InputDataWarning:

The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:257: InputDataWarning:

Input data is not contained to the unit cube. Please consider min-max scaling the input data.

/Users/keisukeonoue/ws/constrained_BO/bo-env/lib/python3.12/site-packages/botorch/models/utils/assorted.py:260: InputDataWarning:

Data is not standardized (std = tensor([0.2667]), mean = tensor([-0.3708])). Please consider scaling the input to zero mean and unit variance.

/Users/keisukeonoue/ws/constrained_BO/src/botorch_wrapper.py:107: InputDataWarning:

The model inputs are of type torch.float32. It is strongly recommended to use doub

In [34]:
bo.train_X

tensor([[-2.0000],
        [10.0000],
        [-1.0000],
        [ 6.0000],
        [ 9.4489],
        [-1.6408],
        [ 0.0000],
        [ 8.0000],
        [ 3.0000]])

In [35]:
bo.train_Y

tensor([[-0.0196],
        [-0.2019],
        [-0.2765],
        [-1.0000],
        [-0.3044],
        [-0.0663],
        [-0.5456],
        [-0.6703],
        [-0.7746]])

In [ ]:
# Generate x values and y values for the test function plot
x = np.linspace(-5, 15, 400)
y = np.exp(-(x - 2) ** 2) + np.exp(-(x - 6) ** 2 / 10) + 1 / (np.exp(x ** 2) + 1)

# Create the plot
fig = go.Figure()

# Plot the test function
fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='test_function'))

# Plot the training data
fig.add_trace(go.Scatter(x=bo.train_X.numpy().flatten(), y=-bo.train_Y.numpy().flatten(), mode='markers', name='train_X'))

# Update layout
fig.update_layout(
    title="Plot of the Test Function and Training Data",
    xaxis_title="x",
    yaxis_title="f(x)"
)

# Show the plot
fig.show()

In [ ]:
#!/usr/bin/env python3
# coding: utf-8

import os
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.optim import optimize_acqf
from botorch.acquisition import ExpectedImprovement
from gpytorch.mlls.exact_marginal_log_likelihood import ExactMarginalLogLikelihood
import matplotlib.pyplot as plt

# デバイスの設定
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.double

# シンプルな2次関数の定義
def objective_function(X):
    return -((X - 2) ** 2).sum(dim=-1)

# 初期データの生成
def generate_initial_data(n=5):
    train_x = torch.rand(n, 1, device=device, dtype=dtype) * 4  # [0, 4]の範囲で初期点を生成
    train_y = objective_function(train_x).unsqueeze(-1)  # 出力次元を追加
    return train_x, train_y

# モデルの初期化
def initialize_model(train_x, train_y):
    model = SingleTaskGP(train_x, train_y)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    return mll, model

# ベイズ最適化ステップを実行する関数
def optimize_acqf_and_get_observation(acq_func):
    candidates, _ = optimize_acqf(
        acq_function=acq_func,
        bounds=bounds,
        q=1,
        num_restarts=10,
        raw_samples=20,
    )
    new_x = candidates.detach()
    new_y = objective_function(new_x).unsqueeze(-1)
    return new_x, new_y

# 問題の設定
bounds = torch.tensor([[0.0], [4.0]], device=device, dtype=dtype)

# 初期データの生成とモデルの初期化
train_x, train_y = generate_initial_data(n=5)
mll, model = initialize_model(train_x, train_y)

# ベイズ最適化ループ
N_BATCH = 15  # 最適化のステップ数
for iteration in range(1, N_BATCH + 1):
    # モデルのフィッティング
    fit_gpytorch_mll(mll)
    
    # EIアクイジション関数の定義
    EI = ExpectedImprovement(model=model, best_f=train_y.max())
    
    # 新しい観測点の取得
    new_x, new_y = optimize_acqf_and_get_observation(EI)
    
    # トレーニングデータの更新
    train_x = torch.cat([train_x, new_x])
    train_y = torch.cat([train_y, new_y])
    
    # モデルの更新
    mll, model = initialize_model(train_x, train_y)