In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3, 4)
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 0.04699392, 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004, 0.9539988 ]])

In [3]:
np.argmax(arr)

11

In [6]:
np.unravel_index(np.argmax(arr), arr.shape)

(2, 3)

In [7]:
arr[2, 3] = np.nan
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 0.04699392, 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004,        nan]])

In [8]:
np.argmax(arr)

11

In [9]:
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 0.04699392, 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004,        nan]])

In [10]:
np.argmin(arr)

11

In [11]:
np.max(arr)

nan

In [12]:
np.nanargmin(arr)

2

In [13]:
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 0.04699392, 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004,        nan]])

In [15]:
arr[(1,1)] = 1
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 1.        , 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004,        nan]])

In [16]:
arr == 1

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [19]:
arr.flatten()

array([0.61435492, 0.08222971, 0.03733625, 0.39744758, 0.90385582,
       1.        , 0.15795978, 0.48188641, 0.80046477, 0.23115418,
       0.06565004,        nan])

In [21]:
np.sort(arr.flatten())[::-1]

array([       nan, 1.        , 0.90385582, 0.80046477, 0.61435492,
       0.48188641, 0.39744758, 0.23115418, 0.15795978, 0.08222971,
       0.06565004, 0.03733625])

In [18]:
np.argsort(arr.flatten())

array([ 2, 10,  1,  6,  9,  3,  7,  0,  8,  4,  5, 11])

In [22]:
arr

array([[0.61435492, 0.08222971, 0.03733625, 0.39744758],
       [0.90385582, 1.        , 0.15795978, 0.48188641],
       [0.80046477, 0.23115418, 0.06565004,        nan]])

In [23]:
np.sum(arr)

nan

In [24]:
np.nansum(arr)

4.772339448613767

In [31]:
arr = np.array([
    [1, 3, 8],
    [4, 3, 2],
    [7, 5, 9]
])

arr

array([[1, 3, 8],
       [4, 3, 2],
       [7, 5, 9]])

In [32]:
np.sort(arr)

array([[1, 3, 8],
       [2, 3, 4],
       [5, 7, 9]])

In [33]:
np.argsort(arr)

array([[0, 1, 2],
       [2, 1, 0],
       [1, 0, 2]])

In [34]:
np.sort(arr.flatten())

array([1, 2, 3, 3, 4, 5, 7, 8, 9])

In [37]:
temp = np.argsort(arr.flatten())
temp

array([0, 5, 1, 4, 3, 7, 6, 2, 8])

In [38]:
np.unravel_index(0, arr.shape)

(0, 0)

In [39]:
for a in temp:
    print(np.unravel_index(a, arr.shape))

(0, 0)
(1, 2)
(0, 1)
(1, 1)
(1, 0)
(2, 1)
(2, 0)
(0, 2)
(2, 2)


In [46]:
arr = arr.astype(float)
arr

array([[1., 3., 8.],
       [4., 3., 2.],
       [7., 5., 9.]])

In [48]:
arr[1,1] = np.nan
arr

array([[ 1.,  3.,  8.],
       [ 4., nan,  2.],
       [ 7.,  5.,  9.]])

In [49]:
np.mean(arr, axis=0)

array([4.        ,        nan, 6.33333333])

In [50]:
np.nanmean(arr, axis=0)

array([4.        , 4.        , 6.33333333])