In [1]:
import numpy as np

In [4]:
temp = [np.random.rand(3, 4) for _ in range(10)]
arr = np.stack(temp, axis=0)
arr

array([[[0.43543598, 0.61301247, 0.12857123, 0.89949054],
        [0.733642  , 0.85798426, 0.14226676, 0.19034511],
        [0.30925033, 0.51889224, 0.63997377, 0.57720045]],

       [[0.11080852, 0.99460498, 0.58709211, 0.3119971 ],
        [0.10656345, 0.76043657, 0.127047  , 0.89776734],
        [0.82576215, 0.67525306, 0.57991611, 0.07309542]],

       [[0.49365748, 0.4126162 , 0.61902648, 0.61711331],
        [0.83396343, 0.18448727, 0.81222925, 0.81270562],
        [0.95888228, 0.82702968, 0.12848978, 0.50068777]],

       [[0.59268185, 0.49984782, 0.69975781, 0.61380758],
        [0.19084116, 0.77768403, 0.15261711, 0.05811087],
        [0.30841159, 0.03159849, 0.5833632 , 0.78291661]],

       [[0.21122743, 0.78995243, 0.71884947, 0.54017135],
        [0.97062728, 0.23462108, 0.39001781, 0.13475372],
        [0.06910504, 0.84113099, 0.76083285, 0.49131367]],

       [[0.23180994, 0.60550923, 0.75973251, 0.75420612],
        [0.34796749, 0.97818096, 0.07580574, 0.31635392],
    

In [5]:
arr.shape

(10, 3, 4)

In [7]:
np.mean(arr, axis=0)

array([[0.29216998, 0.48060895, 0.65352967, 0.49046041],
       [0.52945416, 0.60172396, 0.32935015, 0.37927971],
       [0.52450471, 0.6095271 , 0.53218382, 0.4710241 ]])

In [10]:
import numpy as np
from tensorly.decomposition import parafac
from tensorly.cp_tensor import cp_to_tensor

arr = np.random.rand(3, 4)
print(arr)
factors = parafac(arr, rank=2)

[[0.47315033 0.94511895 0.67997256 0.31152935]
 [0.94816837 0.35741647 0.99823423 0.29755896]
 [0.60466168 0.3037022  0.7341998  0.40704372]]


In [11]:
a, b = factors[0], factors[1]
print(a)
print(b)

[1. 1.]
[array([[ 1.20027708,  0.48545186],
       [ 1.41883617, -0.30150141],
       [ 1.05979782, -0.14615583]]), array([[ 0.55802138, -0.41548013],
       [ 0.42897354,  0.88138987],
       [ 0.65777453, -0.22470924],
       [ 0.26819119,  0.00582375]])]


In [12]:
arr_reconstructed = cp_to_tensor(factors)

In [13]:
arr_reconstructed

array([[0.46808467, 0.94275945, 0.68042617, 0.32473089],
       [0.91700876, 0.34290288, 1.00102445, 0.3787635 ],
       [0.65211468, 0.32580495, 0.72995058, 0.28337726]])

In [14]:
arr

array([[0.47315033, 0.94511895, 0.67997256, 0.31152935],
       [0.94816837, 0.35741647, 0.99823423, 0.29755896],
       [0.60466168, 0.3037022 , 0.7341998 , 0.40704372]])

In [19]:
import numpy as np
from tensorly.decomposition import non_negative_parafac
from tensorly.cp_tensor import cp_to_tensor

arr = np.random.rand(3, 4)
print(arr)
factors = non_negative_parafac(arr, rank=2)
factors

[[0.64696715 0.03737579 0.48585643 0.53243924]
 [0.16446761 0.01027487 0.40266937 0.49121607]
 [0.72507283 0.13635469 0.64150545 0.82656396]]


(weights, factors) : rank-2 CPTensor of shape (3, 4)

In [20]:
arr_reconstructed = cp_to_tensor(factors)
arr_reconstructed

array([[0.64446924, 0.07821508, 0.45995406, 0.55118288],
       [0.16390796, 0.03269523, 0.39353368, 0.49715633],
       [0.72741198, 0.09502556, 0.66483289, 0.81016673]])

In [25]:
arr = np.zeros((3, 4))
arr[0, 0] = 0.4

arr_bool = arr > 0

arr, arr_bool

(array([[0.4, 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ]]),
 array([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]))

In [26]:
arr[arr_bool == 1] = 3

In [27]:
arr

array([[3., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr = np.zeros((3, 4))
arr[0, 0] = 1

(1 - arr).astype(int)

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])