In [4]:
import torch

def test_function(X):
    x = X[:, 0]
    term1 = torch.exp(-(x - 2) ** 2)
    term2 = torch.exp(-((x - 6) / 10) ** 2)
    term3 = 1 / (torch.exp(x ** 2) + 1)
    return term1 + term2 + term3

def schubert_function(X):
    terms = []
    for i in range(X.size(1)):  # d次元に対応
        term = sum(j * torch.cos((j + 1) * X[:, i] + j) for j in range(1, 6))
        terms.append(term)
    return torch.prod(torch.stack(terms, dim=1), dim=1)

def eggholder_function(X):
    x1 = X[:, 0]
    x2 = X[:, 1]
    term1 = -(x2 + 47) * torch.sin(torch.sqrt(torch.abs(x2 + x1 / 2 + 47)))
    term2 = -x1 * torch.sin(torch.sqrt(torch.abs(x1 - (x2 + 47))))
    return term1 + term2

def griewank_function(X):
    sum_term = torch.sum(X ** 2 / 4000, dim=1)
    prod_term = torch.prod(torch.cos(X / torch.sqrt(torch.arange(1, X.size(1) + 1, dtype=X.dtype, device=X.device))), dim=1)
    return sum_term - prod_term + 1

# 使用例:
X_test = torch.tensor([[1.0], [3.0]])
X_schubert = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
X_egg = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
X_griewank = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(test_function(X_test))
print(schubert_function(X_schubert))
print(eggholder_function(X_egg))
print(griewank_function(X_griewank))

tensor([1.4156, 1.2819])
tensor([ 1.4676, -0.0643])
tensor([-34.0888, -43.6555])
tensor([1.0170, 1.5917])


In [14]:
import torch
import numpy as np
import plotly.graph_objs as go

func = test_function

# 2次元グリッドを作成
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)
X, Y = np.meshgrid(x, y)
Z = np.zeros_like(X)

# 各グリッド点でSchubert関数を計算
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        point = torch.tensor([[X[i, j].round(), Y[i, j].round()]], dtype=torch.float32)
        Z[i, j] = func(point).item()

# Plotlyで3Dプロットを作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title='', autosize=False,
                  scene=dict(
                      xaxis_title='x1',
                      yaxis_title='x2',
                      zaxis_title='f(x1, x2)'
                  ))

fig.show()

In [21]:
import torch
import numpy as np
import plotly.graph_objs as go

func = schubert_function

# 2次元グリッドを作成
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)
X, Y = np.meshgrid(x, y)
Z = np.zeros_like(X)

# 各グリッド点でSchubert関数を計算
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        point = torch.tensor([[X[i, j].round(), Y[i, j].round()]], dtype=torch.float32)
        Z[i, j] = func(point).item()

# Plotlyで3Dプロットを作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title='', autosize=False,
                  scene=dict(
                      xaxis_title='x1',
                      yaxis_title='x2',
                      zaxis_title='f(x1, x2)'
                  ))

fig.show()

In [27]:
import torch
import numpy as np
import plotly.graph_objs as go

# Schubert関数を使用する関数の指定
def schubert_function(X):
    terms = []
    for i in range(X.size(1)):  # d次元に対応
        term = sum(j * torch.cos((j + 1) * X[:, i] + j) for j in range(1, 6))
        terms.append(term)
    return torch.prod(torch.stack(terms, dim=1), dim=1)

func = schubert_function

# 離散的な点の範囲を定義
discrete_x = np.arange(-10, 11, 1)
discrete_y = np.arange(-10, 11, 1)
X, Y = np.meshgrid(discrete_x, discrete_y)
Z = np.zeros_like(X)

# 各離散点でSchubert関数を計算
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        point = torch.tensor([[X[i, j], Y[i, j]]], dtype=torch.float32)
        Z[i, j] = func(point).item()

# Zの値が大きい順に上位5つのデータ点を取得
top_indices = np.unravel_index(np.argsort(Z, axis=None)[-5:], Z.shape)
top_x = X[top_indices]
top_y = Y[top_indices]
top_z = Z[top_indices]

# 上位5つのデータ点を出力
for i in range(5):
    print(f"Top {i+1}: x = {top_x[i]}, y = {top_y[i]}, z = {top_z[i]}")

# Plotlyで3Dプロットを作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])

# 上位5つのデータ点を青い点でプロット
fig.add_trace(go.Scatter3d(
    x=top_x,
    y=top_y,
    z=top_z,
    mode='markers',
    marker=dict(
        size=5,
        color='blue',  # 青色で表示
    ),
    name='Top 5 points'
))

fig.update_layout(title='Schubert Function', autosize=False,
                  scene=dict(
                      xaxis_title='x1',
                      yaxis_title='x2',
                      zaxis_title='f(x1, x2)'
                  ))

fig.show()

Top 1: x = -2, y = -7, z = 82
Top 2: x = 5, y = 5, z = 93
Top 3: x = -1, y = -7, z = 108
Top 4: x = -7, y = -1, z = 108
Top 5: x = -7, y = -7, z = 178


In [28]:
discrete_x

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [12]:
import torch
import numpy as np
import plotly.graph_objs as go

func = eggholder_function

# 2次元グリッドを作成
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)
X, Y = np.meshgrid(x, y)
Z = np.zeros_like(X)

# 各グリッド点でSchubert関数を計算
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        point = torch.tensor([[X[i, j].round(), Y[i, j].round()]], dtype=torch.float32)
        Z[i, j] = func(point).item()

# Plotlyで3Dプロットを作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title='', autosize=False,
                  scene=dict(
                      xaxis_title='x1',
                      yaxis_title='x2',
                      zaxis_title='f(x1, x2)'
                  ))

fig.show()

In [11]:
import torch
import numpy as np
import plotly.graph_objs as go

func = griewank_function

# 2次元グリッドを作成
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)
X, Y = np.meshgrid(x, y)
Z = np.zeros_like(X)

# 各グリッド点でSchubert関数を計算
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        point = torch.tensor([[X[i, j].round(), Y[i, j].round()]], dtype=torch.float32)
        Z[i, j] = func(point).item()

# Plotlyで3Dプロットを作成
fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title='', autosize=False,
                  scene=dict(
                      xaxis_title='x1',
                      yaxis_title='x2',
                      zaxis_title='f(x1, x2)'
                  ))

fig.show()

In [14]:
import torch

X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

def objective_function(X):
    return (X**2).sum(dim=-1)

print(f'f(x1) = {objective_function(X1)}')
print(f'f(x2) = {objective_function(X2)}')
print(f'f(x3) = {objective_function(X3)}')
print(f'f(x1).dim = {objective_function(X1).dim()}')
print(f'f(x2).dim = {objective_function(X2).dim()}')
print(f'f(x3).dim = {objective_function(X3).dim()}')

# >>>
# f(x1) = 5.0
# f(x2) = tensor([5.])
# f(x3) = tensor([ 5., 25.])
# f(x1).dim = 0
# f(x2).dim = 1
# f(x3).dim = 1

f(x1) = 5.0
f(x2) = tensor([5.])
f(x3) = tensor([ 5., 25.])
f(x1).dim = 0
f(x2).dim = 1
f(x3).dim = 1


In [4]:
import torch

X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

objective_function = schubert_function

print(f'f(x1) = {objective_function(X1)}')
print(f'f(x2) = {objective_function(X2)}')
print(f'f(x3) = {objective_function(X3)}')

f(x1) = tensor([[1.4676]])
f(x2) = tensor([[1.4676]])
f(x3) = tensor([[ 1.4676],
        [-0.0643]])


In [5]:
def schubert_function(X):
    if X.dim() == 1:
        X = X.unsqueeze(0)  # 1次元のテンソルを2次元に変換
    terms = []
    for i in range(X.size(1)):  # d次元に対応
        term = sum(j * torch.cos((j + 1) * X[:, i] + j) for j in range(1, 6))
        terms.append(term)
    result = torch.prod(torch.stack(terms, dim=1), dim=1)

    # 出力を上のobjective_functionの出力形式に合わせる
    if result.dim() == 0:
        result = result.unsqueeze(0)  # 0次元のテンソル（スカラー）を1次元に変換
    return result

import torch

X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

objective_function = schubert_function

print(f'f(x1) = {objective_function(X1)}')
print(f'f(x2) = {objective_function(X2)}')
print(f'f(x3) = {objective_function(X3)}')

f(x1) = tensor([1.4676])
f(x2) = tensor([1.4676])
f(x3) = tensor([ 1.4676, -0.0643])


In [7]:
objective_function(X1).dim()

1

In [8]:
torch.tensor(2).dim()

0

In [12]:
torch.tensor([1.0, 2.0]).dim()

1

In [13]:
import torch

def schubert_function(X):
    if X.dim() == 1:
        X = X.unsqueeze(0)  # 1次元のテンソルを2次元に変換
    terms = []
    for i in range(X.size(1)):  # d次元に対応
        term = sum(j * torch.cos((j + 1) * X[:, i] + j) for j in range(1, 6))
        terms.append(term)
    result = torch.prod(torch.stack(terms, dim=1), dim=1)
    
    # 入力次元が1次元の場合、スカラー（0次元）を返す
    if result.numel() == 1:
        result = result.squeeze()
    
    return result



X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

objective_function = schubert_function

print(f'f(x1) = {objective_function(X1)}')
print(f'f(x2) = {objective_function(X2)}')
print(f'f(x3) = {objective_function(X3)}')

f(x1) = 1.4675730466842651
f(x2) = 1.4675730466842651
f(x3) = tensor([ 1.4676, -0.0643])


In [15]:
import torch

def schubert_function(X):
    if X.dim() == 1:
        X = X.unsqueeze(0)  # 1次元のテンソルを2次元に変換
    terms = []
    for i in range(X.size(1)):  # d次元に対応
        term = sum(j * torch.cos((j + 1) * X[:, i] + j) for j in range(1, 6))
        terms.append(term)
    result = torch.prod(torch.stack(terms, dim=1), dim=1)
    
    # 入力が1次元の場合、スカラー（0次元）を返す
    if result.numel() == 1:
        result = result.squeeze()
    
    return result

# テストコード
X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print(f'f(x1) = {schubert_function(X1)}')
print(f'f(x2) = {schubert_function(X2)}')
print(f'f(x3) = {schubert_function(X3)}')
print(f'f(x1).dim = {schubert_function(X1).dim()}')
print(f'f(x2).dim = {schubert_function(X2).dim()}')
print(f'f(x3).dim = {schubert_function(X3).dim()}')

f(x1) = 1.4675730466842651
f(x2) = 1.4675730466842651
f(x3) = tensor([ 1.4676, -0.0643])
f(x1).dim = 0
f(x2).dim = 0
f(x3).dim = 1


In [24]:
import torch

def schubert_function(X):
    dtype = X.dtype
    device = X.device
    input_dim = X.dim()

    if X.dim() == 1:
        X = X.unsqueeze(0)  # 1次元のテンソルを2次元に変換

    # jの値を1から5までのテンソルで表現
    j = torch.arange(1, 6, dtype=X.dtype, device=X.device).view(1, -1)
    
    # 各次元のXに対して計算を行う
    X_expanded = X.unsqueeze(-1)  # (n, d, 1) の形に拡張
    terms = j * torch.cos((j + 1) * X_expanded + j)  # (n, d, 5)
    
    # 次元ごとにsumを取って、最終的なprodを取る
    result = torch.prod(terms.sum(dim=-1), dim=-1)  # sumは最後の次元、prodは次元d

    # 出力が1つの要素しかない場合はスカラー（0次元）にする
    if input_dim == 1:
        return torch.tensor(result.item()).to(dtype=dtype).to(device=device)  # スカラー値として返す
    return result

# テストコード
X1 = torch.tensor([1.0, 2.0])
X2 = torch.tensor([[1.0, 2.0]])
X3 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print(f'f(x1) = {schubert_function(X1)}')
print(f'f(x2) = {schubert_function(X2)}')
print(f'f(x3) = {schubert_function(X3)}')
print(f'f(x1).dim = {torch.tensor(schubert_function(X1)).dim()}')
print(f'f(x2).dim = {torch.tensor(schubert_function(X2)).dim()}')
print(f'f(x3).dim = {schubert_function(X3).dim()}')

f(x1) = 1.4675730466842651
f(x2) = tensor([1.4676])
f(x3) = tensor([ 1.4676, -0.0643])
f(x1).dim = 0
f(x2).dim = 1
f(x3).dim = 1


/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_77953/1705718683.py:34: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(f'f(x1).dim = {torch.tensor(schubert_function(X1)).dim()}')
/var/folders/_b/b62kq0490fn2ptq7m4mbp8yr0000gp/T/ipykernel_77953/1705718683.py:35: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(f'f(x2).dim = {torch.tensor(schubert_function(X2)).dim()}')


AttributeError: module 'torch' has no attribute 'tensror'